spring.application.name=API-Gateway

server.port=8888


spring.cloud.gateway.server.webmvc.routes[0].id=Rest_API-1
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**

spring.cloud.gateway.server.webmvc.routes[1].id=Rest_API-2
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/shop/**

