spring.application.name=Rest_API-1


server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/rest-api
spring.datasource.username=root
spring.datasource.password=charan
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

